services:
  - type: web
    name: legend-boys-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false   # Render dashboard mein manually set karna hoga
